### PR TITLE
readme: add shields

### PR DESCRIPTION
**Pull request by umarcor**

### CODE REVIEW

**Review by mithro — CHANGES_REQUESTED** [review]
I think it would be better to **not** embed giant base64 encoded images into our README file.

**Comment by umarcor** [comment]
Should we use a different icon or not use any icon?

These are the available icons without using base64: https://github.com/simple-icons/simple-icons/blob/develop/slugs.md (https://simpleicons.org/)

**Comment by mithro** [comment]
I have generally used https://shields.io/ before.

**Comment by umarcor** [comment]
The shields in this PR are generated through shields.io (all of them). However, shields.io supports icons from simpleicons.org or base64. Therefore, in order to have an F4PGA icon, we need to use base64. Otherwise, we need to use the icon of a different brand (the ones available in simpleicons), or not use any.

**Comment by tmichalak** [comment]
LGTM

**Pull request merged**
